Unregister mousemove when transparent window destroyed (#42)
## The Problem

In commit 01aaef242b92feb25853d16e87ec424f4ae22d44, we updated our
transparent window mouse pass-through strategy for Macs to use a
`mousemove` handler. However, we forgot to check whether the transparent
window has been destroyed before calling
`transparentWindow.setIgnoreMouseEvents()`, so now some users are
getting the [following
error](https://swivvel.sentry.io/issues/4554113703/?project=4504796469657600&query=is%3Aunresolved&referrer=issue-stream&stream_index=0):

> TypeError: Object has been destroyed

## The Solution

Unregister the `mousemove` handler when the transparent window is
destroyed.